### ISSUE TITLE
Add error messages for preconditions in builders

### ISSUE THREAD

**Issue by SgtSilvio** [mqtt-bee/mqtt-bee#136]

**Comment by christianhoff** [comment]
`TopicAliasUsage`is an enum with 5 possible values. 3 for outgoing PUBLISH packets and 2 for incoming PUBLISH packets.

In `Mqtt5PublishBuilder`we use Precondidions.checkArgument to restrict the values of `TopicAliasUsage` to the ones for outgoing PUBLISH packets. That's not very nice. I would prefer to have an Enum that only allows to supply the correct values. Splitting up the enum would also require to have an incoming and outgoing `MqttPublish`. Any thoughts or ideas?

The incoming ones are used by the `Mqtt5PublishDecoder`.

**Comment by SgtSilvio** [comment]
👎 for splitting MqttPublish
But I agree that the enum values are strange.
Maybe we should have 3 options: HAS_NOT, MAY and HAS (not sure about the naming yet) and treat HAS_NOT as a replacement for both HAS_NOT and MUST_NOT and HAS as a replacement for HAS and MAY_OVERWRITE

**Comment by christianhoff** [comment]
* NO (MUST_NOT, HAS_NOT)
  "Indicates that a PUBLISH packet (incoming or outgoing) does not use a topic alias."
* YES (MAY_OVERRIDE, HAS)
  "Indicates that a PUBLISH packet (incoming or outgoing) uses a topic alias. In case of an outgoing PUBLISH packet and if all topic aliases are in use, it will override an existing topic alias."
* IF_AVAILABLE (MAY)
  "Indicates that an outgoing PUBLISH packet uses a topic alias, if there are some unused topic aliases available."
