### ISSUE TITLE
Websocket and Secure Websocket Support

### ISSUE THREAD

**Issue by dobermai** [mqtt-bee/mqtt-bee#82]
MQTT Bee should support Websockets as Transport

Examples can be found here:

https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/http/websocketx/client
https://medium.com/@irunika/how-to-write-a-http-websocket-server-using-netty-f3c136adcba9

**Comment by SgtSilvio** [comment]
Created own issue for secure websocket support #126
