### ISSUE TITLE
MQTT 3 encoders for PubAck, PubRec, PubRel, PubComp are not thread local

### ISSUE THREAD

**Issue by SgtSilvio** [mqtt-bee/mqtt-bee#99]

**Comment by dobermai** [comment]
It's not clear to me why the encoders need to be thread local. What's the rationale?

**Comment by SgtSilvio** [comment]
The encoders are thread local to allow caching of calculated attributes (such as the property length in MQTT 5). For MQTT 3 it does not make a lot of sense, but is implemented the same because the underlying message classes are shared.
